name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DEV_API_URL: ${{ secrets.NEXT_PUBLIC_DEV_API_URL }}
      NEXT_PUBLIC_PROD_API_URL: ${{ secrets.NEXT_PUBLIC_PROD_API_URL }}
      NEXT_PUBLIC_AMPLITUDE_API_KEY: ${{ secrets.NEXT_PUBLIC_AMPLITUDE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Build
        run: npm run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Lint
        run: npm run check:lint
  spell:
    name: Spell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Spell
        run: npm run check:spell
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Install
        run: npm run check:format
